// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kewgoxtctksldnyqyaso.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtld2dveHRjdGtzbGRueXF5YXNvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2MjQwNjMsImV4cCI6MjA2NjIwMDA2M30.Vvtdn_EyxkuczsFad3P0wAG1H_bb53-Y3kg3X8zxzVo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);